Line 1985: self.instrument == 'SED' instead of self.instrument.instrument. Otherwise code gives AttributeError: 'NoneType' object has no attribute 'instrument' and no unresostats can be done!